# file: .github/workflows/release.yml
name: Release Go Binary

on:
  push:
    # This workflow will only run when you push a tag that starts with 'v'
    # For example: v1.0.0, v1.1.2, etc.
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to create a release
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This is needed to allow GoReleaser to fetch all tags
          fetch-depth: 0

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Or your project's Go version

      # Step 3: Run GoReleaser
      # This action does all the magic: builds for multiple platforms,
      # archives the binaries, and creates a GitHub Release.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # The version of GoReleaser to use. 'latest' is fine.
          version: latest
          # The arguments to pass to GoReleaser. 'release --clean' is standard.
          args: release --clean
        env:
          # The GITHUB_TOKEN is automatically created by GitHub Actions.
          # GoReleaser needs it to create the release on your repository.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}